on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build and Test with Gradle
        run: |
          ./gradlew clean test

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/test-results/test


