on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with Gradle
        continue-on-error: true
        run: |
          ./gradlew clean test

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/reports/tests/JUnit/xml/TEST-MainTest.xml


