on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test with Gradle
        continue-on-error: true
        run: |
          ./gradlew clean test

      - name: Publish XML Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results-xml
          if-no-files-found: error
          path: build/reports/tests/JUnit/xml

      - name: Publish HTML Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results-html
          if-no-files-found: error
          path: build/reports/tests/JUnit/html

      - name: Build with Gradle
        run: |
          ./gradlew clean build


